{
  "bugzilla": {
    "description": "python-jose: allows attackers to cause a denial of service",
    "id": "2277300",
    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=2277300"
  },
  "csaw": false,
  "details": [
    "python-jose through 3.3.0 allows attackers to cause a denial of service (resource consumption) during a decode via a crafted JSON Web Encryption (JWE) token with a high compression ratio, aka a \"JWT bomb.\" This is similar to CVE-2024-21319."
  ],
  "name": "CVE-2024-33664",
  "package_state": [
    {
      "cpe": "cpe:/a:redhat:ansible_automation_platform:2",
      "fix_state": "Not affected",
      "package_name": "automation-controller",
      "product_name": "Red Hat Ansible Automation Platform 2"
    },
    {
      "cpe": "cpe:/a:redhat:ansible_automation_platform:2",
      "fix_state": "Not affected",
      "package_name": "python-jose",
      "product_name": "Red Hat Ansible Automation Platform 2"
    }
  ],
  "public_date": "2024-04-26T00:00:00Z",
  "references": [
    "https://www.cve.org/CVERecord?id=CVE-2024-33664\nhttps://nvd.nist.gov/vuln/detail/CVE-2024-33664"
  ],
  "threat_severity": "Moderate"
}